server:
  port: 80
logging:
  level:
      cn.mrxionge.bootdemo: debug
      org.springframework.web: debug
      org.springframework.data: debug
  config: classpath:config/logback.xml
  file:
    max-size: 100M
    max-history: 30
spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    #hikari数据库连接池
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.159:3306/im?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: admin
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariCP
      minimum-idle: 20 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 100 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1 
  http:
     encoding:
      force: true
      charset: UTF-8
      enabled: true
  messages:
       encoding: UTF-8
  mvc:
#      view:
#        prefix: /WEB-INF/view/
#        suffix: .jsp
       throw-exception-if-no-handler-found: true  #找不到对应抛出异常
  servlet:
      multipart:

        location: D:/shangcaitong/
        #location: /var/kehuayouli/
        max-file-size: 10MB
        max-request-size: 10MB
  resources:
      add-mappings: false # false 不开启资源映射
      static-locations: file:${spring.servlet.multipart.location} 
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 1
    jedis:
      pool:
      #最大连接个数
        max-active: 8
        #等待时间
        max-wait: 600ms
        #最大空闲
        max-idle: 8
        #初始化最小
        min-idle: 2
        #操作第几个库
    lettuce:
#      pool:
#        max-active: 8
#        max-wait: 600ms
#        max-idle: 8
#        min-idle: 2
      shutdown-timeout: 200ms
    
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql       
#mybaits-plus相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.khsct.model
  check-config-location: true
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: false
    call-setters-on-nulls: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #MyBatis 自动映射时未知列或未知属性处理策略 NONE：不做任何处理 (默认值), WARNING：以日志的形式打印相关警告信息, FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: warning
     # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      # 可选参数 AUTO->`0`("数据库ID自增") INPUT->`1`(用户输入ID") ID_WORKER->`2`("全局唯一ID")UUID->`3`("全局唯一ID")
      #主键类型  0:"数据库ID自增", 1:"未设置主键类型",2:"用户输入ID (该类型可以通过自己注册自动填充插件进行填充)", 3:"全局唯一ID (idWorker), 4:全局唯一ID (UUID), 5:字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: AUTO
      #字段验证策略 IGNORED:"忽略判断", NOT_NULL:"非NULL判断", NOT_EMPTY:"非空判断", DEFAULT 默认的,一般只用于注解里(1. 在全局里代表 NOT_NULL,2. 在注解里代表 跟随全局)
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除值
      logic-delete-value: 1
      #逻辑未删除值
      logic-not-delete-value: 0
